version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - everything
  rabbit:
    image: rabbitmq:3.8.7-management-alpine
    restart: always
    ports:
      - '15673:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - everything
    environment:
      - "RABBITMQ_DEFAULT_PASS=rabbit"
      - "RABBITMQ_DEFAULT_USER=rabbit"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: 'redis'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - everything
  knapsack-router:
    container_name: knapsack-api
    image: knapsack-engine:0.0.1
    restart: always
    depends_on:
      - rabbit
      - redis
      - knapsack-solver
    ports:
      - '8001:8000'
    environment:
      DEPLOYMENT_TYPE: router
      RABBITMQ_HOST: rabbit
      RABBITMQ_USER: rabbit
      RABBITMQ_PASSWORD: rabbit
      REDIS_HOST: redis
    networks:
      - everything

  knapsack-solver:
    container_name: knapsack-solver
    image: knapsack-engine:0.0.1
    restart: always
    depends_on:
      - rabbit
      - redis
    environment:
      DEPLOYMENT_TYPE: solver
      RABBITMQ_HOST: rabbit
      RABBITMQ_USER: rabbit
      RABBITMQ_PASSWORD: rabbit
      REDIS_HOST: redis
    networks:
      - everything

  knapsack-maintainer:
    container_name: knapsack-maintainer
    image: knapsack-engine:0.0.1
    restart: always
    depends_on:
      - rabbit
      - redis
      - knapsack-solver
    environment:
      DEPLOYMENT_TYPE: maintainer
      RABBITMQ_HOST: rabbit
      RABBITMQ_USER: rabbit
      RABBITMQ_PASSWORD: rabbit
      REDIS_HOST: redis
    networks:
      - everything

volumes:
  db:
    driver: local

networks:
  everything:
    driver: bridge